

version: '2.0'

services:

  prometheus:
    image: prometheus/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
      - 9999:9090
    extra_hosts:
      - "orderer0.example.com:192.168.1.4"
      - "orderer1.example.com:192.168.1.4"
      - "orderer2.example.com:192.168.1.4"
      - "peer0.org1.example.com:192.168.1.4"
      - "peer1.org1.example.com:192.168.1.4"
      - "peer0.org2.example.com:192.168.1.4"
      - "peer1.org2.example.com:192.168.1.4"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.0.0
    restart: always
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
